services:
  chromeless:
    image: browserless/chrome:latest
    container_name: chromeless
    environment:
      - MAX_CONCURRENT_SESSIONS=15
      - MAX_QUEUE_LENGTH=15
      - CONNECTION_TIMEOUT=60000
      - PREBOOT_CHROME=true
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - DEFAULT_USER_DATA_DIR=/tmp/chrome
      - PROXY_SSL=true
      - DEFAULT_LAUNCH_ARGS=["--window-size=2560,1920", "--no-sandbox", "--disable-dev-shm-usage"]
    ports:
     - "3000:3000"
